# Generated by Django 5.2.8 on 2025-11-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_components_featured_image'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Components',
            new_name='Component',
        ),
    ]
